# Generated by Django 5.2.8 on 2025-11-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_attendant_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendant',
            name='archived',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('patient', 'Patient'), ('admin', 'Staff'), ('owner', 'Owner'), ('attendant', 'Attendant')], default='patient', max_length=10),
        ),
    ]
