# Generated by Django 5.2.1 on 2025-11-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_feedback_rating_alter_feedback_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='closedday',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
