# Generated by Django 5.2.1 on 2025-11-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_closedday_archived_notification_archived_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closedday',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='smstemplate',
            name='archived',
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='template_type',
            field=models.CharField(choices=[('confirmation', 'Appointment Confirmation'), ('reminder', 'Appointment Reminder'), ('cancellation', 'Cancellation Notification'), ('package_confirmation', 'Package Confirmation'), ('attendant_reassignment', 'Attendant Reassignment'), ('custom', 'Custom Template')], max_length=30),
        ),
    ]
